version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION_STRING: postgres://postgres:postgres@postgres:5432/postgres
      REDIS_HOST: redis:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "7777:80"
    networks:
      - backend-network

  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "postgres", "-h", "127.0.0.1", "-p", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    networks:
      - backend-network

  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - backend-network

volumes:
  cache:
    driver: local

networks:
  backend-network:
    driver: bridge