definitions:
  feeds.Feed:
    properties:
      district_id:
        type: integer
      volunteer_data:
        type: integer
    type: object
  feeds.Response:
    properties:
      count:
        type: integer
      results:
        items:
          $ref: '#/definitions/feeds.Feed'
        type: array
    type: object
host: localhost:80
info:
  contact:
    name: Acik Kaynak
  description: Musahit Harita API
  license:
    name: Apache 2.0
    url: https://github.com/acikkaynak/musahit-harita-backend/blob/main/LICENSE
  title: Musahit Harita API
  version: "1.0"
paths:
  /feeds:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.Response'
      summary: Get Feeds
      tags:
      - Feed
  /feeds/mock:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.Response'
      summary: Get Feeds mock
      tags:
      - Feed
swagger: "2.0"
