definitions:
  feeds.Feed:
    properties:
      neighborhood_id:
        type: integer
      volunteer_data:
        type: integer
    type: object
  feeds.FeedDetail:
    properties:
      ballotBoxNos:
        items:
          type: integer
        type: array
      buildingName:
        type: string
    type: object
  feeds.FeedDetailResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/feeds.FeedDetail'
        type: array
      intensity:
        type: integer
      lastUpdateTime:
        type: string
      neighborhoodId:
        type: integer
    type: object
  feeds.Response:
    properties:
      count:
        type: integer
      results:
        items:
          $ref: '#/definitions/feeds.Feed'
        type: array
    type: object
host: localhost:80
info:
  contact:
    name: Acik Kaynak
  description: Musahit Harita API
  license:
    name: Apache 2.0
    url: https://github.com/acikkaynak/musahit-harita-backend/blob/main/LICENSE
  title: Musahit Harita API
  version: "1.0"
paths:
  /feed/{neighborhoodId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.FeedDetailResponse'
      summary: Get Feed Detail
      tags:
      - Feed
  /feeds:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.Response'
      summary: Get Feeds
      tags:
      - Feed
  /mock/feed/{neighborhoodId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.FeedDetailResponse'
      summary: Get Feed Detail mock
      tags:
      - Feed
  /mock/feeds:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/feeds.Response'
      summary: Get Feeds mock
      tags:
      - Feed
swagger: "2.0"
